// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/components/button": {
    params: {};
  };
  "/components/floating-menu": {
    params: {};
  };
  "/components/icon": {
    params: {};
  };
  "/components/loader": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/components/button" | "/components/floating-menu" | "/components/icon" | "/components/loader";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/root/layout.tsx": {
    id: "routes/root/layout";
    page: "/components/button" | "/components/floating-menu" | "/components/icon" | "/components/loader";
  };
  "common/button/button-route.tsx": {
    id: "common/button/button-route";
    page: "/components/button";
  };
  "common/floating-menu/floating-menu-route.tsx": {
    id: "common/floating-menu/floating-menu-route";
    page: "/components/floating-menu";
  };
  "common/icon/icon-route.tsx": {
    id: "common/icon/icon-route";
    page: "/components/icon";
  };
  "common/loader/loader-route.tsx": {
    id: "common/loader/loader-route";
    page: "/components/loader";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/root/layout": typeof import("./app/routes/root/layout.tsx");
  "common/button/button-route": typeof import("./app/common/button/button-route.tsx");
  "common/floating-menu/floating-menu-route": typeof import("./app/common/floating-menu/floating-menu-route.tsx");
  "common/icon/icon-route": typeof import("./app/common/icon/icon-route.tsx");
  "common/loader/loader-route": typeof import("./app/common/loader/loader-route.tsx");
};