// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/components/badge": {
    params: {};
  };
  "/components/badge-affix": {
    params: {};
  };
  "/components/breadcrumb": {
    params: {};
  };
  "/components/checkbox": {
    params: {};
  };
  "/components/checkbox-field": {
    params: {};
  };
  "/components/button": {
    params: {};
  };
  "/components/floating-menu": {
    params: {};
  };
  "/components/icon": {
    params: {};
  };
  "/components/input": {
    params: {};
  };
  "/components/input-field": {
    params: {};
  };
  "/components/loader": {
    params: {};
  };
  "/components/modal": {
    params: {};
  };
  "/components/textarea": {
    params: {};
  };
  "/components/textarea-field": {
    params: {};
  };
  "/components/toggle": {
    params: {};
  };
  "/components/tooltip": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/components/badge" | "/components/badge-affix" | "/components/breadcrumb" | "/components/checkbox" | "/components/checkbox-field" | "/components/button" | "/components/floating-menu" | "/components/icon" | "/components/input" | "/components/input-field" | "/components/loader" | "/components/modal" | "/components/textarea" | "/components/textarea-field" | "/components/toggle" | "/components/tooltip";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/root/layout.tsx": {
    id: "routes/root/layout";
    page: "/components/badge" | "/components/badge-affix" | "/components/breadcrumb" | "/components/checkbox" | "/components/checkbox-field" | "/components/button" | "/components/floating-menu" | "/components/icon" | "/components/input" | "/components/input-field" | "/components/loader" | "/components/modal" | "/components/textarea" | "/components/textarea-field" | "/components/toggle" | "/components/tooltip";
  };
  "common/badge/badge-route.tsx": {
    id: "common/badge/badge-route";
    page: "/components/badge";
  };
  "common/badge-affix/badge-affix-route.tsx": {
    id: "common/badge-affix/badge-affix-route";
    page: "/components/badge-affix";
  };
  "common/breadcrumb/breadcrumb-route.tsx": {
    id: "common/breadcrumb/breadcrumb-route";
    page: "/components/breadcrumb";
  };
  "common/checkbox/checkbox-route.tsx": {
    id: "common/checkbox/checkbox-route";
    page: "/components/checkbox";
  };
  "common/checkbox/checkbox-field-route.tsx": {
    id: "common/checkbox/checkbox-field-route";
    page: "/components/checkbox-field";
  };
  "common/button/button-route.tsx": {
    id: "common/button/button-route";
    page: "/components/button";
  };
  "common/floating-menu/floating-menu-route.tsx": {
    id: "common/floating-menu/floating-menu-route";
    page: "/components/floating-menu";
  };
  "common/icon/icon-route.tsx": {
    id: "common/icon/icon-route";
    page: "/components/icon";
  };
  "common/input/input-route.tsx": {
    id: "common/input/input-route";
    page: "/components/input";
  };
  "common/input/input-field-route.tsx": {
    id: "common/input/input-field-route";
    page: "/components/input-field";
  };
  "common/loader/loader-route.tsx": {
    id: "common/loader/loader-route";
    page: "/components/loader";
  };
  "common/modal/modal-route.tsx": {
    id: "common/modal/modal-route";
    page: "/components/modal";
  };
  "common/textarea/textarea-route.tsx": {
    id: "common/textarea/textarea-route";
    page: "/components/textarea";
  };
  "common/textarea/textarea-field-route.tsx": {
    id: "common/textarea/textarea-field-route";
    page: "/components/textarea-field";
  };
  "common/toggle/toggle-route.tsx": {
    id: "common/toggle/toggle-route";
    page: "/components/toggle";
  };
  "common/tooltip/tooltip-route.tsx": {
    id: "common/tooltip/tooltip-route";
    page: "/components/tooltip";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/root/layout": typeof import("./app/routes/root/layout.tsx");
  "common/badge/badge-route": typeof import("./app/common/badge/badge-route.tsx");
  "common/badge-affix/badge-affix-route": typeof import("./app/common/badge-affix/badge-affix-route.tsx");
  "common/breadcrumb/breadcrumb-route": typeof import("./app/common/breadcrumb/breadcrumb-route.tsx");
  "common/checkbox/checkbox-route": typeof import("./app/common/checkbox/checkbox-route.tsx");
  "common/checkbox/checkbox-field-route": typeof import("./app/common/checkbox/checkbox-field-route.tsx");
  "common/button/button-route": typeof import("./app/common/button/button-route.tsx");
  "common/floating-menu/floating-menu-route": typeof import("./app/common/floating-menu/floating-menu-route.tsx");
  "common/icon/icon-route": typeof import("./app/common/icon/icon-route.tsx");
  "common/input/input-route": typeof import("./app/common/input/input-route.tsx");
  "common/input/input-field-route": typeof import("./app/common/input/input-field-route.tsx");
  "common/loader/loader-route": typeof import("./app/common/loader/loader-route.tsx");
  "common/modal/modal-route": typeof import("./app/common/modal/modal-route.tsx");
  "common/textarea/textarea-route": typeof import("./app/common/textarea/textarea-route.tsx");
  "common/textarea/textarea-field-route": typeof import("./app/common/textarea/textarea-field-route.tsx");
  "common/toggle/toggle-route": typeof import("./app/common/toggle/toggle-route.tsx");
  "common/tooltip/tooltip-route": typeof import("./app/common/tooltip/tooltip-route.tsx");
};