// This file is generated by icon spritesheet generator

export const iconNames = [
  "xmark",
  "star",
  "sidebar",
  "person-to-portal",
  "magnifying-glass",
  "linkedin",
  "house",
  "github",
  "caret-down",
  "bluesky",
  "bars",
  "bars-filter",
  "angle-right",
] as const;

export type IconName = (typeof iconNames)[number];
